- name: Create a test file with timestamp
  hosts: all
  become: yes
  tasks:
    - name: Get current timestamp
      ansible.builtin.command: date +"%Y%m%d_%H%M%S"
      register: timestamp
      changed_when: false

    - name: Create a file in /home with timestamp
      ansible.builtin.file:
        path: "/home/test_{{ timestamp.stdout }}"
        state: touch
        mode: '0644'